// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCzxJZOHL2KOAf7MEhqmksOk4NhSL71Y',
    appId: '1:595446281868:web:7cfe9bff38d764b25d6da9',
    messagingSenderId: '595446281868',
    projectId: 'aiassistant-6ec0e',
    authDomain: 'aiassistant-6ec0e.firebaseapp.com',
    storageBucket: 'aiassistant-6ec0e.firebasestorage.app',
    measurementId: 'G-WS12BLL05N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4z3460bo9-hlgLWWSQZfZJRmxNdG97c',
    appId: '1:595446281868:android:173870e5667165565d6da9',
    messagingSenderId: '595446281868',
    projectId: 'aiassistant-6ec0e',
    storageBucket: 'aiassistant-6ec0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1NMzlzyMe3F-tRM3jRBEermDjOfphV8',
    appId: '1:595446281868:ios:912c28181fe858ff5d6da9',
    messagingSenderId: '595446281868',
    projectId: 'aiassistant-6ec0e',
    storageBucket: 'aiassistant-6ec0e.firebasestorage.app',
    iosBundleId: 'com.example.aiassistant1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1NMzlzyMe3F-tRM3jRBEermDjOfphV8',
    appId: '1:595446281868:ios:912c28181fe858ff5d6da9',
    messagingSenderId: '595446281868',
    projectId: 'aiassistant-6ec0e',
    storageBucket: 'aiassistant-6ec0e.firebasestorage.app',
    iosBundleId: 'com.example.aiassistant1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALCzxJZOHL2KOAf7MEhqmksOk4NhSL71Y',
    appId: '1:595446281868:web:a367fd2dc616f8e85d6da9',
    messagingSenderId: '595446281868',
    projectId: 'aiassistant-6ec0e',
    authDomain: 'aiassistant-6ec0e.firebaseapp.com',
    storageBucket: 'aiassistant-6ec0e.firebasestorage.app',
    measurementId: 'G-LPEM6RC8YK',
  );
}
